# usaremos una imagen base oficial de python
FROM python:3.10-slim

# establecer el directorio de trabajo
WORKDIR /app

# copiar los archivos de la aplicación
COPY app.py .

# comando a ejecutar al iniciar el contenedor
CMD ["python3", "app.py"]
